@startuml

title Context Diagram for CozyCove

actor Guest
actor Host
actor CustomerSupportAgent
actor PaymentGateway
actor EmailService
actor SMSService

Guest -right-> (CozyCove): Use
Host -right-> (CozyCove): Use
CustomerSupportAgent -left-> (CozyCove): Support

(CozyCove) .> PaymentGateway: Process Payments
(CozyCove) .> EmailService: Send Emails
(CozyCove) .> SMSService: Send SMS

@enduml
