@startuml

title Context Diagram for Airbnb-like Platform

actor Guest
actor Host
actor CustomerSupportAgent
actor PaymentGateway
actor EmailService
actor SMSService

Guest -right-> (Airbnb Platform): Use
Host -right-> (Airbnb Platform): Use
CustomerSupportAgent -left-> (Airbnb Platform): Support

(Airbnb Platform) .> PaymentGateway: Process Payments
(Airbnb Platform) .> EmailService: Send Emails
(Airbnb Platform) .> SMSService: Send SMS

@enduml
